### ISSUE TITLE
『バックアップを作成するフォルダ』初期値のスペル名に誤りがある

### ISSUE THREAD

**Issue by setohima** [MinadukiSekina/VRCToolBox#47]
（こういった類の報告をするのは初めてなので、書き方に何か問題点があればご指摘ください）

**概要**
『バックアップを作成するフォルダ』の初期値のスペル名に誤りがあります。
誤：（前略）VRCToolBox\ProjectB**u**ckups
正：（前略）VRCToolBox\ProjectB**a**ckups

**再現手順**
1. VRCToolBox_Installer.msiで各画面で初期値のままインストールを完了する。
2. インストール後に開いたVRCToolBoxの『設定』→『Unity』→『バックアップを作成するフォルダ』の値を確認する。

**問題個所のスクリーンショット**
![スクリーンショット 2022-10-24 093256](https://user-images.githubusercontent.com/29247171/197426413-df8b6e29-3f8e-4b3f-8137-c50e05fd93e0.png)
『バックアップを作成するフォルダ』の末尾がProjectB**u**ckupsになっている。ProjectB**a**ckupsが正しい綴りだと思われる。

**投稿者の環境情報:**
 - OS: Windows 10 Home
 - Version: 21H2 (OSビルド: 19044.2130)
 - Program Version: v0.6.5

**Comment by MinadukiSekina** [comment]
issueありがとうございます。
なるはやで修正しようと思います！
