### ISSUE TITLE
特定条件下で写真の移動完了時に操作不能になる

### ISSUE THREAD

**Issue by setohima** [MinadukiSekina/VRCToolBox#51]
**Describe the bug**
ホーム画面で『写真の移動』をクリックし、処理終了時までずっとホーム画面のままでいると処理終了時の独自UI？によるメッセージボックスがVRCToolBox本体の背面に表示された状態になり、それを前面に持ってくることができないためVRCToolBox本体が操作不能になる。

**To Reproduce**
1. VRChatのスクリーンショットを複数枚用意しておく
2. ホーム画面で『写真の移動』をクリックする
3. 処理が終了するまでホーム画面で待つ
4. 処理が終了するとVRCToolBox本体の背面に処理完了のメッセージボックスが表示され、本体が操作不能になる

**Expected behavior**
ホーム画面での処理終了時に処理完了のメッセージボックスが表面に表示される

**Screenshots**
![image](https://user-images.githubusercontent.com/29247171/199284104-3597d982-48c3-43dd-a611-85bd6a376cf9.png)
※このとき、本体の画面のどこをクリックしても『メッセージボックスが出ている時にそれ以外の場所をクリックした時と同じ効果音』が再生されるため、操作を受け付けない状態。

**Desktop (please complete the following information):**
- OS: Windows 10 Home
- Version: 21H2 (OSビルド: 19044.2130)
- Program Version: v0.6.6

**Additional context**
手順3の途中でホーム画面以外に移動する、例えばUnityや写真の画面を開いていると手順4のタイミングが処理完了のメッセージボックスが前面に表示される。

**Comment by setohima** [comment]
追記：
- 移動する写真がない状態で手順を試すと、正常に移動完了のメッセージボックスが前面に表示される。
- 『ログの移動』ではこの現象は発生しない。こちらは独自UIのメッセージボックスではなくwindows標準のメッセージボックスを使っている点が差異？

**Comment by MinadukiSekina** [comment]
私の環境（OSなど同じ）では再現しなかったのですが、改善策を実装予定です。
